### ISSUE TITLE
Is it actually a polyfill?

### ISSUE THREAD

**Issue by p0o** [LinusU/wext-storage#1]
Thanks for this, I am so surprised someone think about exactly what I needed. However, you used the word `polyfill` but if the extension API is not available (like web environment for example) this API does not provide any solutions AFAIK.

The thing is when I'm building my UI on storybook, I like to have an actual polyfill to provide coverage for the functionalities like storing data. Could probably use Session Storage for temporary storage maybe. What do you think?

**Comment by LinusU** [comment]
Hmm, the idea with this module was to polyfill the W3C WebExtension API on _extension_ platforms that don't support it (e.g. Chrome Extensions, Safari Extensions). It wasn't meant to bring the extension intended API to normal web pages.

What is your use case for this? I think that you would be better served by [fanny-pack](https://github.com/LinusU/fanny-pack) which works on multiple platforms (including in browser extensions by using this very module).

If you want to have the same code for a Browser Extension and a website you could use the `@fanny-pack/browser` and `@fanny-pack/browser-extension` packages ☺️

**Comment by p0o** [comment]
Well, I'm not building a website, but I'm using [Storybook](https://storybook.js.org) to build the UI for my extension. So essentially it will run on the web only in development mode.

I checked fanny-pack, it's nice but the thing is I should write checks to detect the environment and import the correct library. It's doable but not exactly what I'm looking for. I would be more interested to use wext-storage as a lightweight solution and it works in any environment whatsoever. But I guess you're not interested for this package to go that way right?

**Comment by LinusU** [comment]
> Well, I'm not building a website, but I'm using Storybook to build the UI for my extension.

Is the UI code tightly coupled to the persistence layer? It seems like the UI should just display dummy data when being rendered in the Storybook?

> I would be more interested to use wext-storage as a lightweight solution and it works in any environment whatsoever.

The problem is that some of the API doesn't really have something equivalent in the browser, e.g. `storage.sync` and `storage.managed`. Thus it wouldn't map cleanly as a browser polyfill 🤔

**Comment by p0o** [comment]
> Is the UI code tightly coupled to the persistence layer? It seems like the UI should just display dummy data when being rendered in the Storybook?

You can say it is tightly coupled since I'm using useEffect hook to manage side effects. Meaning that rendering container components will lead to the execution of real storage functions. Basically you can pass props and dummy actions to your components but that's it. If there's an internal function running based on a lifecycle, you can't do much about it in a standard way.

>The problem is that some of the API doesn't really have something equivalent in the browser, e.g. storage.sync and storage.managed. Thus it wouldn't map cleanly as a browser polyfill

Yeah I get the problem, makes total sense. I guess I will give your fanny-pack a try. Thanks
